version: "2"

services:
  sibcoind_d:
      image: docker-sibcoind
      build: containers/sibcoind/.
      volumes:
        - "/srv/sibcoind_data:/data/sibcoin"
      network_mode: "service:electrumx_d"
      depends_on:
        - electrumx_d

  electrumx_d:
    image: electrumx
    build: containers/electrumx/.
    env_file:
      - ".electrumx.env"
    volumes:
      - "/srv/electrumx_data:/srv/db"
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8000:8000"
