version: "2"

services:
  sibcoind_d:
      image: docker-sibcoind
      build: containers/sibcoind/.
      volumes:
        - "/srv/sibcoind_data:/data/sibcoin"
      network_mode: "service:electrumx_d"
      depends_on:
        - electrumx_d

  electrumx_d:
    image: electrumx
    build: containers/electrumx/.
    environment:
      - DB_DIRECTORY=/srv/db
      - DAEMON_URL=http://sibcoin:local321@localhost:1944
      - HOST=
      - TCP_PORT=50001
      - COIN=Sibcoin
      - SSL_PORT=50002
      - SSL_CERTFILE=/srv/db/server.crt
      - SSL_KEYFILE=/srv/db/server.key
      - DONATION_ADDRESS=Sb52XrTGMSojZAcDpvbpyi2h6FPEp74ypY
    volumes:
      - "/srv/electrumx_data:/srv/db"
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8000:8000"
    expose:
      - 50001
      - 50002
